//
// readregisters.c
//
// DO NOT EDIT THIS FILE.  This file was generated automatically
// by a script that converts an assembler listing into a C structure
// containing the hex values of the instructions in the listing.
// You must edit the assembler source directly and execute the build
// again.
//

static unsigned int aui_readregisters_code[] =
tgt_compile(\
".set noat\n" \
"1:dmtc0 t7,c0_desave;\n" \
"lui t7,0xff20;\n" \
"sd zero,FIFO(t7);\n" \
"sd at,FIFO(t7);\n" \
"dmfc0 t7,c0_desave;\n" \
"dmtc0 at,c0_desave;\n" \
"lui at,0xff20;\n" \
"sd v0,FIFO(at);\n" \
"sd v1,FIFO(at);\n" \
"sd a0,FIFO(at);\n" \
"sd a1,FIFO(at);\n" \
"sd a2,FIFO(at);\n" \
"sd a3,FIFO(at);\n" \
"sd t0,FIFO(at);\n" \
"sd t1,FIFO(at);\n" \
"sd t2,FIFO(at);\n" \
"sd t3,FIFO(at);\n" \
"sd t4,FIFO(at);\n" \
"sd t5,FIFO(at);\n" \
"sd t6,FIFO(at);\n" \
"sd t7,FIFO(at);\n" \
"sd s0,FIFO(at);\n" \
"sd s1,FIFO(at);\n" \
"sd s2,FIFO(at);\n" \
"sd s3,FIFO(at);\n" \
"sd s4,FIFO(at);\n" \
"sd s5,FIFO(at);\n" \
"sd s6,FIFO(at);\n" \
"sd s7,FIFO(at);\n" \
"sd t8,FIFO(at);\n" \
"sd t9,FIFO(at);\n" \
"sd k0,FIFO(at);\n" \
"sd k1,FIFO(at);\n" \
"sd gp,FIFO(at);\n" \
"sd sp,FIFO(at);\n" \
"sd s8,FIFO(at);\n" \
"sd ra,FIFO(at);\n" \
"sd v0,STACK(at);\n" \
"dmfc0 v0,c0_status;\n" \
"sd v0,FIFO(at);\n" \
"mflo v0;\n" \
"sd v0,FIFO(at);\n" \
"mfhi v0;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_badvaddr;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_cause;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_depc;\n" \
"sd v0,FIFO(at);\n" \
"lui at,0xff20;\n" \
"ld v0,STACK(at);\n" \
"dmfc0 at,c0_desave;\n" \
"sync;\n" \
"b 1b;\n" \
"nop ;\n" \
);

static unsigned int aui_readregisters_all_code[] =
tgt_compile(\
".set noat\n" \
"1:dmtc0 t7,c0_desave;\n" \
"lui t7,0xff20;\n" \
"sd zero,FIFO(t7);\n" \
"sd at,FIFO(t7);\n" \
"dmfc0 t7,c0_desave;\n" \
"dmtc0 at,c0_desave;\n" \
"lui at,0xff20;\n" \
"sd v0,FIFO(at);\n" \
"sd v1,FIFO(at);\n" \
"sd a0,FIFO(at);\n" \
"sd a1,FIFO(at);\n" \
"sd a2,FIFO(at);\n" \
"sd a3,FIFO(at);\n" \
"sd t0,FIFO(at);\n" \
"sd t1,FIFO(at);\n" \
"sd t2,FIFO(at);\n" \
"sd t3,FIFO(at);\n" \
"sd t4,FIFO(at);\n" \
"sd t5,FIFO(at);\n" \
"sd t6,FIFO(at);\n" \
"sd t7,FIFO(at);\n" \
"sd s0,FIFO(at);\n" \
"sd s1,FIFO(at);\n" \
"sd s2,FIFO(at);\n" \
"sd s3,FIFO(at);\n" \
"sd s4,FIFO(at);\n" \
"sd s5,FIFO(at);\n" \
"sd s6,FIFO(at);\n" \
"sd s7,FIFO(at);\n" \
"sd t8,FIFO(at);\n" \
"sd t9,FIFO(at);\n" \
"sd k0,FIFO(at);\n" \
"sd k1,FIFO(at);\n" \
"sd gp,FIFO(at);\n" \
"sd sp,FIFO(at);\n" \
"sd s8,FIFO(at);\n" \
"sd ra,FIFO(at);\n" \
"sd v0,STACK(at);\n" \
"dmfc0 v0,c0_status;\n" \
"sd v0,FIFO(at);\n" \
"mflo v0;\n" \
"sd v0,FIFO(at);\n" \
"mfhi v0;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_badvaddr;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_cause;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_depc;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_status;\n" \
"srl	v0,v0,16;\n" \
"andi	v0,v0,0x2000;\n" \
"beqz	v0,2f;\n" \
"nop;\n" \
"sdc1	$0,FIFO(at);\n" \
"sdc1	$1,FIFO(at);\n" \
"sdc1	$2,FIFO(at);\n" \
"sdc1	$3,FIFO(at);\n" \
"sdc1	$4,FIFO(at);\n" \
"sdc1	$5,FIFO(at);\n" \
"sdc1	$6,FIFO(at);\n" \
"sdc1	$7,FIFO(at);\n" \
"sdc1	$8,FIFO(at);\n" \
"sdc1	$9,FIFO(at);\n" \
"sdc1	$10,FIFO(at);\n" \
"sdc1	$11,FIFO(at);\n" \
"sdc1	$12,FIFO(at);\n" \
"sdc1	$13,FIFO(at);\n" \
"sdc1	$14,FIFO(at);\n" \
"sdc1	$15,FIFO(at);\n" \
"sdc1	$16,FIFO(at);\n" \
"sdc1	$17,FIFO(at);\n" \
"sdc1	$18,FIFO(at);\n" \
"sdc1	$19,FIFO(at);\n" \
"sdc1	$20,FIFO(at);\n" \
"sdc1	$21,FIFO(at);\n" \
"sdc1	$22,FIFO(at);\n" \
"sdc1	$23,FIFO(at);\n" \
"sdc1	$24,FIFO(at);\n" \
"sdc1	$25,FIFO(at);\n" \
"sdc1	$26,FIFO(at);\n" \
"sdc1	$27,FIFO(at);\n" \
"sdc1	$28,FIFO(at);\n" \
"sdc1	$29,FIFO(at);\n" \
"sdc1	$30,FIFO(at);\n" \
"sdc1	$31,FIFO(at);\n" \
"cfc1	v0,c1_status;\n" \
"sw	v0,FIFO(at);\n" \
"cfc1	v0,c1_revision;\n" \
"sw	v0,FIFO(at);\n" \
"2:lui at,0xff20;\n" \
"ld v0,STACK(at);\n" \
"dmfc0 at,c0_desave;\n" \
"sync;\n" \
"b 1b;\n" \
"nop ;\n" \
);

static unsigned int aui_readregisters_all_help_code[] =
tgt_compile(\
".set noat\n" \
"1:dmtc0 t7,c0_desave;\n" \
"lui t7,0xff20;\n" \
"sd zero,FIFO(t7);\n" \
"sd at,FIFO(t7);\n" \
"dmfc0 t7,c0_desave;\n" \
"dmtc0 at,c0_desave;\n" \
"lui at,0xff20;\n" \
"sd v0,FIFO(at);\n" \
"sd v1,FIFO(at);\n" \
"sd a0,FIFO(at);\n" \
"sd a1,FIFO(at);\n" \
"sd a2,FIFO(at);\n" \
"sd a3,FIFO(at);\n" \
"sd t0,FIFO(at);\n" \
"sd t1,FIFO(at);\n" \
"sd t2,FIFO(at);\n" \
"sd t3,FIFO(at);\n" \
"sd t4,FIFO(at);\n" \
"sd t5,FIFO(at);\n" \
"sd t6,FIFO(at);\n" \
"sd t7,FIFO(at);\n" \
"sd s0,FIFO(at);\n" \
"sd s1,FIFO(at);\n" \
"sd s2,FIFO(at);\n" \
"sd s3,FIFO(at);\n" \
"sd s4,FIFO(at);\n" \
"sd s5,FIFO(at);\n" \
"sd s6,FIFO(at);\n" \
"sd s7,FIFO(at);\n" \
"sd t8,FIFO(at);\n" \
"sd t9,FIFO(at);\n" \
"sd k0,FIFO(at);\n" \
"sd k1,FIFO(at);\n" \
"sd gp,FIFO(at);\n" \
"sd sp,FIFO(at);\n" \
"sd s8,FIFO(at);\n" \
"sd ra,FIFO(at);\n" \
"sd v0,STACK(at);\n" \
"dmfc0 v0,c0_status;\n" \
"sd v0,FIFO(at);\n" \
"mflo v0;\n" \
"sd v0,FIFO(at);\n" \
"mfhi v0;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_badvaddr;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_cause;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_depc;\n" \
"sd v0,FIFO(at);\n" \
"dmfc0 v0,c0_status;\n" \
"srl	v0,v0,16;\n" \
"andi	v0,v0,0x2000;\n" \
"beqz	v0,2f;\n" \
"nop;\n" \
"sd   v1, STACK(at);\n" \
"ld   v0, PARAM(at);\n" \
"sdc1   $0, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $1, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $2, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $3, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $4, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $5, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $6, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $7, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $8, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $9, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $10, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $11, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $12, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $13, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $14, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $15, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $16, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $17, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $18, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $19, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $20, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $21, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $22, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $23, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $24, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $25, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $26, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $27, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $28, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $29, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $30, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"sdc1   $31, (v0);\n"  \
"ld	v1, (v0);\n" \
"sd	v1, FIFO(at);\n" \
"cfc1	v0,c1_status;\n" \
"sw	v0,FIFO(at);\n" \
"cfc1	v0,c1_revision;\n" \
"sw	v0,FIFO(at);\n" \
"ld   v1, STACK(at);\n" \
"2:lui at,0xff20;\n" \
"ld v0,STACK(at);\n" \
"dmfc0 at,c0_desave;\n" \
"sync;\n" \
"b 1b;\n" \
"nop ;\n" \
);
